# Generated by Django 5.1.4 on 2025-02-04 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainy', '0002_chatbotquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatbotQuery',
        ),
    ]
